version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
  build:
    commands:
      - echo Build started on `date`
      - npm install
artifacts:
  files:
    - '**/*'
  discard-paths: no